### ISSUE TITLE
Only White Screen

### ISSUE THREAD

**Issue by deshan** [anandmuralidhar24/SimpleARAndroid#1]
Thanks for the project and nice tutorial!

When I run the project I see only  a white screen. Any ideas?

Thanks

**Comment by anandmuralidhar24** [comment]
Hi deshan, can you upload the logcat? It is probably failing to create a GL window but I need to check the logs to confirm.

**Comment by deshan** [comment]
Thanks for the reply.

This is the log

> 12-19 08:25:33.524: E/SimpleARAndroid(3494): Error in compiling fragment shader
> 12-19 08:25:33.524: A/SimpleARAndroid(3494): error in uniform: textureSampler
> 12-19 08:25:33.524: A/SimpleARAndroid(3494): Error in getting attribute: vertexPosition
> 12-19 08:25:33.534: A/SimpleARAndroid(3494): [FAIL GL] BackTexture::BackTexture
> 12-19 08:25:33.534: E/SimpleARAndroid(3494): GL_INVALID_VALUE: numeric argument out of range
> 12-19 08:25:33.544: E/SimpleARAndroid(3494): Error in compiling fragment shader
> 12-19 08:25:33.544: A/SimpleARAndroid(3494): Error in getting attribute: vertexPosition
> 12-19 08:25:33.544: A/SimpleARAndroid(3494): Error in getting attribute: vertexUV
> 12-19 08:25:33.544: A/SimpleARAndroid(3494): error in uniform: mvpMat
> 12-19 08:25:33.544: A/SimpleARAndroid(3494): error in uniform: textureSampler
> 12-19 08:25:33.544: A/SimpleARAndroid(3494): [FAIL GL] AssimpLoader::AssimpLoader
> 12-19 08:25:33.544: E/SimpleARAndroid(3494): GL_INVALID_VALUE: numeric argument out of range
> 12-19 08:25:34.184: A/SimpleARAndroid(3494): [FAIL GL] BackTexture::Render
> 12-19 08:25:34.184: E/SimpleARAndroid(3494): GL_INVALID_OPERATION: operation illegal in current state
> 12-19 08:25:34.194: A/SimpleARAndroid(3494): [FAIL GL] BackTexture::Render
> 12-19 08:25:34.194: E/SimpleARAndroid(3494): GL_INVALID_OPERATION: operation illegal in current state
> 12-19 08:25:34.204: A/SimpleARAndroid(3494): [FAIL GL] BackTexture::Render
> 12-19 08:25:34.204: E/SimpleARAndroid(3494): GL_INVALID_OPERATION: operation illegal in current state
> 12-19 08:25:34.214: A/SimpleARAndroid(3494): [FAIL GL] BackTexture::Render

**Comment by anandmuralidhar24** [comment]
Thanks for sending the log. This is only a portion of it and indicates that none of GLES operations are working correctly. Please upload the logs from the beginning so that we can check if a GLES instance was created correctly. Also let me know your device model.

**Comment by deshan** [comment]
Thanks below is the completely log on Samsung galaxy s6




12-21 08:34:02.269: W/ResourcesManager(16987): getTopLevelResources:
/data/app/com.anandmuralidhar.simplearandroid-2/base.apk / 1.0 running
in com.anandmuralidhar.simplearandroid rsrc of package
com.anandmuralidhar.simplearandroid
12-21 08:34:02.269: I/InjectionManager(16987): Inside getClassLibPath
+ mLibMap{0=, 1=}
12-21 08:34:02.269: D/ResourcesManager(16987): For user 0 new overlays
fetched Null
12-21 08:34:02.279: I/InjectionManager(16987): Inside getClassLibPath caller
12-21 08:34:02.279: D/InjectionManager(16987): InjectionManager
12-21 08:34:02.279: D/InjectionManager(16987): fillFeatureStoreMap
com.anandmuralidhar.simplearandroid
12-21 08:34:02.279: I/InjectionManager(16987): Constructor
com.anandmuralidhar.simplearandroid, Feature store :{}
12-21 08:34:02.279: I/InjectionManager(16987): featureStore :{}
12-21 08:34:02.319: W/ResourcesManager(16987): getTopLevelResources:
/data/app/com.anandmuralidhar.simplearandroid-2/base.apk / 1.0 running
in com.anandmuralidhar.simplearandroid rsrc of package
com.anandmuralidhar.simplearandroid
12-21 08:34:02.319: W/ResourcesManager(16987): getTopLevelResources:
/data/app/com.anandmuralidhar.simplearandroid-2/base.apk / 1.0 running
in com.anandmuralidhar.simplearandroid rsrc of package
com.anandmuralidhar.simplearandroid
12-21 08:34:02.369: D/CameraClass(16987): Got a camera instance
12-21 08:34:02.379: D/CameraClass(16987): Setting preview resolution to 1280x720
12-21 08:34:02.379: D/CameraClass(16987): FOV for Landscape 41.592663
12-21 08:34:02.379: D/CameraClass(16987): Setting focus mode to
FOCUS_MODE_CONTINUOUS_VIDEO
12-21 08:34:02.379: D/SimpleARAndroid(16987): SimpleARClass::SimpleARClass
12-21 08:34:02.419: D/Activity(16987): performCreate Call Injection manager
12-21 08:34:02.419: I/InjectionManager(16987): dispatchOnViewCreated >
Target : com.anandmuralidhar.simplearandroid.SimpleARActivity
isFragment :false
12-21 08:34:02.419: D/SensorClass(16987): Registering sensors
12-21 08:34:02.429: D/SensorManager(16987): registerListener :: 0,
MPU6500 Acceleration Sensor, 20000, 0,
12-21 08:34:02.429: D/CameraClass(16987): Starting camera preview
12-21 08:34:02.619: D/SecWifiDisplayUtil(16987): Metadata value : SecSettings2
12-21 08:34:02.629: D/ViewRootImpl(16987): #1 mView =
com.android.internal.policy.PhoneWindow$DecorView{8953073 I.E......
R.....ID 0,0-0,0}
12-21 08:34:02.639: D/OpenGLRenderer(16987): Use
EGL_SWAP_BEHAVIOR_PRESERVED: true
12-21 08:34:02.689: D/libEGL(16987): loaded /vendor/lib/egl/libGLES_mali.so
12-21 08:34:02.709: D/libEGL(16987): eglInitialize EGLDisplay = 0xe9bff7c4
12-21 08:34:02.709: I/OpenGLRenderer(16987): Initialized EGL, version 1.4
12-21 08:34:02.709: D/(16987): ro.exynos.dss isEnabled: 0
12-21 08:34:02.709: D/mali_winsys(16987): new_window_surface returns
0x3000,  [2560x1440]-format:1
12-21 08:34:02.719: D/libEGL(16987): eglInitialize EGLDisplay = 0xee6b94c4
12-21 08:34:02.719: D/(16987): ro.exynos.dss isEnabled: 0
12-21 08:34:02.729: D/mali_winsys(16987): new_window_surface returns
0x3000,  [2560x1184]-format:2
12-21 08:34:02.729: D/MyGLRenderer(16987): onSurfaceCreated
12-21 08:34:02.729: D/SimpleARAndroid(16987): SimpleARClass::PerformGLInits
12-21 08:34:02.729: I/SimpleARAndroid(16987): OpenGL OpenGL ES 3.1
v1.r7p0-03rel0.b596bd02e7d0169c10574b57180c8b57, GLSL OpenGL ES GLSL
ES 3.10
12-21 08:34:02.729: D/SimpleARAndroid(16987): Device supports GLES 3
12-21 08:34:02.729: I/SimpleARAndroid(16987): Reading shader: shaders/back.vsh
12-21 08:34:02.729: I/SimpleARAndroid(16987): Asset extracted:
/data/user/0/com.anandmuralidhar.simplearandroid/files/back.vsh
12-21 08:34:02.729: I/SimpleARAndroid(16987): Read successfully
12-21 08:34:02.729: I/SimpleARAndroid(16987): Compiling shader
12-21 08:34:02.739: I/SimpleARAndroid(16987): Compiled shader successfully
12-21 08:34:02.739: I/SimpleARAndroid(16987): Reading shader: shaders/back.fsh
12-21 08:34:02.739: I/SimpleARAndroid(16987): Asset extracted:
/data/user/0/com.anandmuralidhar.simplearandroid/files/back.fsh
12-21 08:34:02.739: I/SimpleARAndroid(16987): Read successfully
12-21 08:34:02.739: I/SimpleARAndroid(16987): Compiling shader
12-21 08:34:02.739: I/SimpleARAndroid(16987): Failed to compile shader
12-21 08:34:02.739: I/SimpleARAndroid(16987): 0:21: S0032: no default
precision defined for variable 'textureCoords'
12-21 08:34:02.739: E/SimpleARAndroid(16987): Error in compiling fragment shader
12-21 08:34:02.739: A/SimpleARAndroid(16987): error in uniform: textureSampler
12-21 08:34:02.739: A/SimpleARAndroid(16987): Error in getting
attribute: vertexPosition
12-21 08:34:02.739: D/libGLESv2(16987): DTS_GLAPI : DTS is not allowed
for Package : com.anandmuralidhar.simplearandroid
12-21 08:34:02.739: A/SimpleARAndroid(16987): [FAIL GL] BackTexture::BackTexture
12-21 08:34:02.739: E/SimpleARAndroid(16987): GL_INVALID_VALUE:
numeric argument out of range
12-21 08:34:02.739: I/SimpleARAndroid(16987): Reading shader:
shaders/modelTextured.vsh
12-21 08:34:02.739: W/DisplayListCanvas(16987): DisplayListCanvas is
started on unbinded RenderNode (without mOwningView)
12-21 08:34:02.739: D/libGLESv1(16987): DTS_GLAPI : DTS is not allowed
for Package : com.anandmuralidhar.simplearandroid
12-21 08:34:02.739: I/SimpleARAndroid(16987): Asset extracted:
/data/user/0/com.anandmuralidhar.simplearandroid/files/modelTextured.vsh
12-21 08:34:02.739: I/SimpleARAndroid(16987): Read successfully
12-21 08:34:02.739: I/SimpleARAndroid(16987): Compiling shader
12-21 08:34:02.739: I/SimpleARAndroid(16987): Compiled shader successfully
12-21 08:34:02.739: I/SimpleARAndroid(16987): Reading shader:
shaders/modelTextured.fsh
12-21 08:34:02.739: I/SimpleARAndroid(16987): Asset extracted:
/data/user/0/com.anandmuralidhar.simplearandroid/files/modelTextured.fsh
12-21 08:34:02.739: I/SimpleARAndroid(16987): Read successfully
12-21 08:34:02.739: I/SimpleARAndroid(16987): Compiling shader
12-21 08:34:02.739: I/SimpleARAndroid(16987): Failed to compile shader
12-21 08:34:02.739: I/SimpleARAndroid(16987): 0:20: S0032: no default
precision defined for variable 'textureCoords'
12-21 08:34:02.739: E/SimpleARAndroid(16987): Error in compiling fragment shader
12-21 08:34:02.739: A/SimpleARAndroid(16987): Error in getting
attribute: vertexPosition
12-21 08:34:02.739: A/SimpleARAndroid(16987): Error in getting
attribute: vertexUV
12-21 08:34:02.739: A/SimpleARAndroid(16987): error in uniform: mvpMat
12-21 08:34:02.739: A/SimpleARAndroid(16987): error in uniform: textureSampler
12-21 08:34:02.739: A/SimpleARAndroid(16987): [FAIL GL]
AssimpLoader::AssimpLoader
12-21 08:34:02.739: E/SimpleARAndroid(16987): GL_INVALID_VALUE:
numeric argument out of range
12-21 08:34:02.759: I/SimpleARAndroid(16987): Asset extracted:
/data/user/0/com.anandmuralidhar.simplearandroid/files/amenemhat.obj
12-21 08:34:02.759: I/SimpleARAndroid(16987): Asset extracted:
/data/user/0/com.anandmuralidhar.simplearandroid/files/amenemhat.mtl
12-21 08:34:02.759: I/SimpleARAndroid(16987): Asset extracted:
/data/user/0/com.anandmuralidhar.simplearandroid/files/amenemhat.jpg
12-21 08:34:02.759: I/SimpleARAndroid(16987): Scene will be imported now
12-21 08:34:02.799: E/(16987): g2d stretchFimgApi_v5 function does not exist
12-21 08:34:02.799: E/(16987): [JM] stretchFimgApi might be v4.
12-21 08:34:02.839: I/InjectionManager(16987):
dispatchCreateOptionsMenu
:com.anandmuralidhar.simplearandroid.SimpleARActivity
12-21 08:34:02.839: I/InjectionManager(16987):
dispatchPrepareOptionsMenu
:com.anandmuralidhar.simplearandroid.SimpleARActivity
12-21 08:34:02.839: D/ViewRootImpl(16987): MSG_RESIZED_REPORT:
ci=Rect(0, 96 - 0, 0) vi=Rect(0, 96 - 0, 0) or=2



On Tue, Dec 20, 2016 at 9:22 AM Anand Muralidhar <notifications@github.com>
wrote:

Thanks for sending the log. This is only a portion of it and indicates that
none of GLES operations are working correctly. Please upload the logs from
the beginning so that we can check if a GLES instance was created
correctly. Also let me know your device model.




—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/anandmuralidhar24/SimpleARAndroid/issues/1#issuecomment-268147884>,
or mute the thread

**Comment by anandmuralidhar24** [comment]
Thanks for sending the log. This issue was because the fragment shader was missing the <code>precision</code> qualifier for <code>float</code>. I've added it and it should work now. Please let me know if you see other issues.

**Comment by deshan** [comment]
Great Application works fine
