### ISSUE TITLE
keypoints are highlighted in the image before input for detection

### ISSUE THREAD

**Issue by deshan** [anandmuralidhar24/SimpleARAndroid#3]
Hi Anand,

See the code below.

```
bool SimpleARClass::DetectKeypointsInReferenceImage() {
cameraMutex.lock();
cv::imwrite( "/sdcard/img.jpg", cameraImageForBack ); // save cameraImageForBack here
cornerDetector->detectAndCompute(cameraImageForBack,....
....
```
Attached is the saved image, is this normal?
Because image highlighted with feature points input to the _detectAndCompute_ method

![img 0 1](https://cloud.githubusercontent.com/assets/234754/21741420/1ed313ba-d4fb-11e6-9e7b-06d6afdad548.jpg)
Thanks
chamika

**Comment by anandmuralidhar24** [comment]
Hi chamika,

Good catch, this was a bug wherein `cameraImageForBack` used as the reference image had corners marked in it! I've fixed the issue by moving all corner detection operations to `SimpleARClass::ProcessCameraImage`.
You should be able to save the image from that function. Please test it and let me know if it works.

best,
Anand

**Comment by deshan** [comment]
Great! It is ok now.
Thanks Anand
