### ISSUE TITLE
Crash - couldn't find "libSimpleARNative.so"                                                                                        at 

### ISSUE THREAD

**Issue by kantbinh** [anandmuralidhar24/SimpleARAndroid#4]
```
Process: com.anandmuralidhar.simplearandroid, PID: 6790
                                                                                   java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.anandmuralidhar.simplearandroid-2/base.apk"],nativeLibraryDirectories=[/data/app/com.anandmuralidhar.simplearandroid-2/lib/arm, /system/fake-libs, /data/app/com.anandmuralidhar.simplearandroid-2/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]] couldn't find "libSimpleARNative.so"
                                                                                       at java.lang.Runtime.loadLibrary0(Runtime.java:984)
                                                                                       at java.lang.System.loadLibrary(System.java:1562)
                                                                                       at 
com.anandmuralidhar.simplearandroid.SimpleARActivity.<clinit>(SimpleARActivity.java:154)

```

I got crash when launch the app as this line

```
static {
        System.loadLibrary("SimpleARNative");
    }
```

Can you help please ? Thanks

**Comment by anandmuralidhar24** [comment]
Looks like the library is not getting built for your phone. Can you let me know your device,ABI, and android version?
The project will run on devices with ABI armeabi-v7a and will fail on other ABIs.

**Comment by kantbinh** [comment]
@anandmuralidhar24 
My device is XiaomiA1 run Android 7.1.2,  ABI arm64-v8a

**Comment by anandmuralidhar24** [comment]
thanks for the confirmation, this project will not run on devices with that ABI since some of the libs (assimp) are built only for armeabi-v7a.

**Comment by kantbinh** [comment]
Hi @anandmuralidhar24 ,

By the way, could you please tell me which SDK I should follow to implement AR on native android ?

**Comment by anandmuralidhar24** [comment]
I'm not sure if there is any SDK for native android implementation. Most AR SDKs might provide enough functionality to avoid programming in native. You can look at ARCore by Google to see if it satisfies your requirements.
